<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>64fb512f-8add-4d17-b453-a29d8dc57c70</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Inventory\Inventory.Api\InventorySystem.Inventory.Api.csproj" />
    <ProjectReference Include="..\Services\Catalog\Catalog.Api\InventorySystem.Catalog.Api.csproj" />
    <ProjectReference Include="..\Services\ScanGateway\ScanGateway.Api\InventorySystem.ScanGateway.Api.csproj" />
    <ProjectReference Include="..\Services\Dashboard\Dashboard.Api\InventorySystem.Dashboard.Api.csproj" />
    <ProjectReference Include="..\Services\Notification\Notification.Api\InventorySystem.Notification.Api.csproj" />
    <ProjectReference Include="..\Services\Staff\Staff.Api\InventorySystem.Staff.Api.csproj" />
  </ItemGroup>

</Project>
